# Site settings
title: นครศรี Travel
email: your-email@domain.com
url: https://azynxtw.github.io
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
baseurl: "/azy"



# Build settings
markdown: kramdown

