
# Site settings
title: Nakhone Sri | Travel

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://azynxtw.github.io/azy/" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
